## System states
##   state can change to next state in 2 ways:
##   - a process emits a GotoSystemState signal with state name to goto
##   - objects specified in EXIT_STATE_DEPEND have started
SYSTEM_STATES = [
    'BASE_APPS',
    'BMC_STARTING',
    'BMC_READY',
    'HOST_POWERING_ON',
    'HOST_POWERED_ON',
    'HOST_BOOTING',
    'HOST_BOOTED',
    'HOST_POWERED_OFF',
]

EXIT_STATE_DEPEND = {
    'BASE_APPS' : {
        '/org/openbmc/sensors': 0,
    },
    'BMC_STARTING' : {
        '/org/openbmc/control/chassis0': 0,
        '/org/openbmc/control/power0' : 0,
        '/org/openbmc/control/host0' : 0,
        '/org/openbmc/control/flash/bios' : 0,
    },
}

FRU_INSTANCES = {
    '<inventory_root>/system' : { 'fru_type' : 'SYSTEM','is_fru' : True, 'present' : "True" },
    '<inventory_root>/system/misc' : { 'fru_type' : 'SYSTEM','is_fru' : False, },

    '<inventory_root>/system/chassis' : { 'fru_type' : 'SYSTEM','is_fru' : True, 'present' : "True" },

    '<inventory_root>/system/chassis/motherboard' : { 'fru_type' : 'MAIN_PLANAR','is_fru' : True, },

    '<inventory_root>/system/systemevent'                  : { 'fru_type' : 'SYSTEM_EVENT', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/refclock' : { 'fru_type' : 'MAIN_PLANAR', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/pcieclock': { 'fru_type' : 'MAIN_PLANAR', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/todclock' : { 'fru_type' : 'MAIN_PLANAR', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/apss'     : { 'fru_type' : 'MAIN_PLANAR', 'is_fru' : False, },

    '<inventory_root>/system/chassis/motherboard/bmc' : { 'fru_type' : 'BMC','is_fru' : False, 'manufacturer' : 'ASPEED' },

    '<inventory_root>/system/chassis/motherboard/cpu0' : { 'fru_type' : 'CPU', 'is_fru' : True, },
    '<inventory_root>/system/chassis/motherboard/cpu1' : { 'fru_type' : 'CPU', 'is_fru' : True, },
    '<inventory_root>/system/chassis/motherboard/cpu2' : { 'fru_type' : 'CPU', 'is_fru' : True, },
    '<inventory_root>/system/chassis/motherboard/cpu3' : { 'fru_type' : 'CPU', 'is_fru' : True, },

    '<inventory_root>/system/chassis/motherboard/cpu0/core0' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core1' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core2' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core3' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core4' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core5' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core6' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core7' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core8' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core9' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core10': { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu0/core11': { 'fru_type' : 'CORE', 'is_fru' : False, },

    '<inventory_root>/system/chassis/motherboard/cpu1/core0' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core1' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core2' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core3' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core4' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core5' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core6' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core7' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core8' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core9' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core10' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu1/core11' : { 'fru_type' : 'CORE', 'is_fru' : False, },

    '<inventory_root>/system/chassis/motherboard/cpu2/core0' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core1' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core2' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core3' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core4' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core5' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core6' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core7' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core8' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core9' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core10' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu2/core11' : { 'fru_type' : 'CORE', 'is_fru' : False, },

    '<inventory_root>/system/chassis/motherboard/cpu3/core0' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core1' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core2' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core3' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core4' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core5' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core6' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core7' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core8' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core9' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core10' : { 'fru_type' : 'CORE', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/cpu3/core11' : { 'fru_type' : 'CORE', 'is_fru' : False, },

    '<inventory_root>/system/chassis/motherboard/membuf0' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf1' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf2' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf3' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf4' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf5' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf6' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf7' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf8' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf9' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf10' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf11' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf12' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf13' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf14' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },
    '<inventory_root>/system/chassis/motherboard/membuf15' : { 'fru_type' : 'MEMORY_BUFFER', 'is_fru' : False, },

    '<inventory_root>/system/chassis/motherboard/dimm0' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm1' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm2' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm3' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm4' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm5' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm6' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm7' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm8' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm9' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm10' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm11' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm12' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm13' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm14' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm15' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm16' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm17' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm18' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm19' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm20' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm21' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm22' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm23' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm24' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm25' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm26' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm27' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm28' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm29' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm30' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm31' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm32' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm33' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm34' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm35' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm36' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm37' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm38' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm39' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm40' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm41' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm42' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm43' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm44' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm45' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm46' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm47' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm48' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm49' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm50' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm51' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm52' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm53' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm54' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm55' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm56' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm57' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm58' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm59' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm60' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm61' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm62' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm63' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm64' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm65' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm66' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm67' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm68' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm69' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm70' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm71' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm72' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm73' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm74' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm75' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm76' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm77' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm78' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm79' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm80' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm81' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm82' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm83' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm84' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm85' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm86' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm87' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm88' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm89' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm90' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm91' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm92' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm93' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm94' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm95' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm96' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm97' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm98' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm99' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm100' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm101' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm102' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm103' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm104' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm105' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm106' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm107' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm108' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm109' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm110' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm111' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm112' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm113' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm114' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm115' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm116' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm117' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm118' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm119' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm120' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm121' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm122' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm123' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm124' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm125' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm126' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/dimm127' : { 'fru_type' : 'DIMM', 'is_fru' : True,},
    '<inventory_root>/system/chassis/motherboard/bios' : { 'fru_type' : 'SYSTEM','is_fru' : True,},
}

ID_LOOKUP = {
    'FRU' : {
        0x01 : '<inventory_root>/system/chassis/motherboard/cpu0',
        0x02 : '<inventory_root>/system/chassis/motherboard/cpu1',
        0x03 : '<inventory_root>/system/chassis/motherboard/cpu2',
        0x04 : '<inventory_root>/system/chassis/motherboard/cpu3',
        0x05 : '<inventory_root>/system/chassis/motherboard',
        0x06 : '<inventory_root>/system/chassis/motherboard/membuf0',
        0x07 : '<inventory_root>/system/chassis/motherboard/membuf1',
        0x08 : '<inventory_root>/system/chassis/motherboard/membuf2',
        0x09 : '<inventory_root>/system/chassis/motherboard/membuf3',
        0x0a : '<inventory_root>/system/chassis/motherboard/membuf4',
        0x0b : '<inventory_root>/system/chassis/motherboard/membuf5',
        0x0c : '<inventory_root>/system/chassis/motherboard/membuf6',
        0x0d : '<inventory_root>/system/chassis/motherboard/membuf7',
        0x0e : '<inventory_root>/system/chassis/motherboard/membuf8',
        0x0f : '<inventory_root>/system/chassis/motherboard/membuf9',
        0x10 : '<inventory_root>/system/chassis/motherboard/membuf10',
        0x11 : '<inventory_root>/system/chassis/motherboard/membuf11',
        0x12 : '<inventory_root>/system/chassis/motherboard/membuf12',
        0x13 : '<inventory_root>/system/chassis/motherboard/membuf13',
        0x14 : '<inventory_root>/system/chassis/motherboard/membuf14',
        0x15 : '<inventory_root>/system/chassis/motherboard/membuf15',
        0x16 : '<inventory_root>/system/chassis/motherboard/dimm0',
        0x17 : '<inventory_root>/system/chassis/motherboard/dimm1',
        0x18 : '<inventory_root>/system/chassis/motherboard/dimm2',
        0x19 : '<inventory_root>/system/chassis/motherboard/dimm3',
        0x1a : '<inventory_root>/system/chassis/motherboard/dimm4',
        0x1b : '<inventory_root>/system/chassis/motherboard/dimm5',
        0x1c : '<inventory_root>/system/chassis/motherboard/dimm6',
        0x1d : '<inventory_root>/system/chassis/motherboard/dimm7',
        0x1e : '<inventory_root>/system/chassis/motherboard/dimm8',
        0x1f : '<inventory_root>/system/chassis/motherboard/dimm9',
        0x20 : '<inventory_root>/system/chassis/motherboard/dimm10',
        0x21 : '<inventory_root>/system/chassis/motherboard/dimm11',
        0x22 : '<inventory_root>/system/chassis/motherboard/dimm12',
        0x23 : '<inventory_root>/system/chassis/motherboard/dimm13',
        0x24 : '<inventory_root>/system/chassis/motherboard/dimm14',
        0x25 : '<inventory_root>/system/chassis/motherboard/dimm15',
        0x26 : '<inventory_root>/system/chassis/motherboard/dimm16',
        0x27 : '<inventory_root>/system/chassis/motherboard/dimm17',
        0x28 : '<inventory_root>/system/chassis/motherboard/dimm18',
        0x29 : '<inventory_root>/system/chassis/motherboard/dimm19',
        0x2a : '<inventory_root>/system/chassis/motherboard/dimm20',
        0x2b : '<inventory_root>/system/chassis/motherboard/dimm21',
        0x2c : '<inventory_root>/system/chassis/motherboard/dimm22',
        0x2d : '<inventory_root>/system/chassis/motherboard/dimm23',
        0x2e : '<inventory_root>/system/chassis/motherboard/dimm24',
        0x2f : '<inventory_root>/system/chassis/motherboard/dimm25',
        0x30 : '<inventory_root>/system/chassis/motherboard/dimm26',
        0x31 : '<inventory_root>/system/chassis/motherboard/dimm27',
        0x32 : '<inventory_root>/system/chassis/motherboard/dimm28',
        0x33 : '<inventory_root>/system/chassis/motherboard/dimm29',
        0x34 : '<inventory_root>/system/chassis/motherboard/dimm30',
        0x35 : '<inventory_root>/system/chassis/motherboard/dimm31',
        0x36 : '<inventory_root>/system/chassis/motherboard/dimm32',
        0x37 : '<inventory_root>/system/chassis/motherboard/dimm33',
        0x38 : '<inventory_root>/system/chassis/motherboard/dimm34',
        0x39 : '<inventory_root>/system/chassis/motherboard/dimm35',
        0x3a : '<inventory_root>/system/chassis/motherboard/dimm36',
        0x3b : '<inventory_root>/system/chassis/motherboard/dimm37',
        0x3c : '<inventory_root>/system/chassis/motherboard/dimm38',
        0x3d : '<inventory_root>/system/chassis/motherboard/dimm39',
        0x3e : '<inventory_root>/system/chassis/motherboard/dimm40',
        0x3f : '<inventory_root>/system/chassis/motherboard/dimm41',
        0x40 : '<inventory_root>/system/chassis/motherboard/dimm42',
        0x41 : '<inventory_root>/system/chassis/motherboard/dimm43',
        0x42 : '<inventory_root>/system/chassis/motherboard/dimm44',
        0x43 : '<inventory_root>/system/chassis/motherboard/dimm45',
        0x44 : '<inventory_root>/system/chassis/motherboard/dimm46',
        0x45 : '<inventory_root>/system/chassis/motherboard/dimm47',
        0x46 : '<inventory_root>/system/chassis/motherboard/dimm48',
        0x47 : '<inventory_root>/system/chassis/motherboard/dimm49',
        0x48 : '<inventory_root>/system/chassis/motherboard/dimm50',
        0x49 : '<inventory_root>/system/chassis/motherboard/dimm51',
        0x4a : '<inventory_root>/system/chassis/motherboard/dimm52',
        0x4b : '<inventory_root>/system/chassis/motherboard/dimm53',
        0x4c : '<inventory_root>/system/chassis/motherboard/dimm54',
        0x4d : '<inventory_root>/system/chassis/motherboard/dimm55',
        0x4e : '<inventory_root>/system/chassis/motherboard/dimm56',
        0x4f : '<inventory_root>/system/chassis/motherboard/dimm57',
        0x50 : '<inventory_root>/system/chassis/motherboard/dimm58',
        0x51 : '<inventory_root>/system/chassis/motherboard/dimm59',
        0x52 : '<inventory_root>/system/chassis/motherboard/dimm60',
        0x53 : '<inventory_root>/system/chassis/motherboard/dimm61',
        0x54 : '<inventory_root>/system/chassis/motherboard/dimm62',
        0x55 : '<inventory_root>/system/chassis/motherboard/dimm63',
        0x56 : '<inventory_root>/system/chassis/motherboard/dimm64',
        0x57 : '<inventory_root>/system/chassis/motherboard/dimm65',
        0x58 : '<inventory_root>/system/chassis/motherboard/dimm66',
        0x59 : '<inventory_root>/system/chassis/motherboard/dimm67',
        0x5a : '<inventory_root>/system/chassis/motherboard/dimm68',
        0x5b : '<inventory_root>/system/chassis/motherboard/dimm69',
        0x5c : '<inventory_root>/system/chassis/motherboard/dimm70',
        0x5d : '<inventory_root>/system/chassis/motherboard/dimm71',
        0x5e : '<inventory_root>/system/chassis/motherboard/dimm72',
        0x5f : '<inventory_root>/system/chassis/motherboard/dimm73',
        0x60 : '<inventory_root>/system/chassis/motherboard/dimm74',
        0x61 : '<inventory_root>/system/chassis/motherboard/dimm75',
        0x62 : '<inventory_root>/system/chassis/motherboard/dimm76',
        0x63 : '<inventory_root>/system/chassis/motherboard/dimm77',
        0x64 : '<inventory_root>/system/chassis/motherboard/dimm78',
        0x65 : '<inventory_root>/system/chassis/motherboard/dimm79',
        0x66 : '<inventory_root>/system/chassis/motherboard/dimm80',
        0x67 : '<inventory_root>/system/chassis/motherboard/dimm81',
        0x68 : '<inventory_root>/system/chassis/motherboard/dimm82',
        0x69 : '<inventory_root>/system/chassis/motherboard/dimm83',
        0x6a : '<inventory_root>/system/chassis/motherboard/dimm84',
        0x6b : '<inventory_root>/system/chassis/motherboard/dimm85',
        0x6c : '<inventory_root>/system/chassis/motherboard/dimm86',
        0x6d : '<inventory_root>/system/chassis/motherboard/dimm87',
        0x6e : '<inventory_root>/system/chassis/motherboard/dimm88',
        0x6f : '<inventory_root>/system/chassis/motherboard/dimm89',
        0x70 : '<inventory_root>/system/chassis/motherboard/dimm90',
        0x71 : '<inventory_root>/system/chassis/motherboard/dimm91',
        0x72 : '<inventory_root>/system/chassis/motherboard/dimm92',
        0x73 : '<inventory_root>/system/chassis/motherboard/dimm93',
        0x74 : '<inventory_root>/system/chassis/motherboard/dimm94',
        0x75 : '<inventory_root>/system/chassis/motherboard/dimm95',
        0x76 : '<inventory_root>/system/chassis/motherboard/dimm96',
        0x77 : '<inventory_root>/system/chassis/motherboard/dimm97',
        0x78 : '<inventory_root>/system/chassis/motherboard/dimm98',
        0x79 : '<inventory_root>/system/chassis/motherboard/dimm99',
        0x7a : '<inventory_root>/system/chassis/motherboard/dimm100',
        0x7b : '<inventory_root>/system/chassis/motherboard/dimm101',
        0x7c : '<inventory_root>/system/chassis/motherboard/dimm102',
        0x7d : '<inventory_root>/system/chassis/motherboard/dimm103',
        0x7e : '<inventory_root>/system/chassis/motherboard/dimm104',
        0x7f : '<inventory_root>/system/chassis/motherboard/dimm105',
        0x80 : '<inventory_root>/system/chassis/motherboard/dimm106',
        0x81 : '<inventory_root>/system/chassis/motherboard/dimm107',
        0x82 : '<inventory_root>/system/chassis/motherboard/dimm108',
        0x83 : '<inventory_root>/system/chassis/motherboard/dimm109',
        0x84 : '<inventory_root>/system/chassis/motherboard/dimm110',
        0x85 : '<inventory_root>/system/chassis/motherboard/dimm111',
        0x86 : '<inventory_root>/system/chassis/motherboard/dimm112',
        0x87 : '<inventory_root>/system/chassis/motherboard/dimm113',
        0x88 : '<inventory_root>/system/chassis/motherboard/dimm114',
        0x89 : '<inventory_root>/system/chassis/motherboard/dimm115',
        0x8a : '<inventory_root>/system/chassis/motherboard/dimm116',
        0x8b : '<inventory_root>/system/chassis/motherboard/dimm117',
        0x8c : '<inventory_root>/system/chassis/motherboard/dimm118',
        0x8d : '<inventory_root>/system/chassis/motherboard/dimm119',
        0x8e : '<inventory_root>/system/chassis/motherboard/dimm120',
        0x8f : '<inventory_root>/system/chassis/motherboard/dimm121',
        0x90 : '<inventory_root>/system/chassis/motherboard/dimm122',
        0x91 : '<inventory_root>/system/chassis/motherboard/dimm123',
        0x92 : '<inventory_root>/system/chassis/motherboard/dimm124',
        0x93 : '<inventory_root>/system/chassis/motherboard/dimm125',
        0x94 : '<inventory_root>/system/chassis/motherboard/dimm126',
        0x95 : '<inventory_root>/system/chassis/motherboard/dimm127',
        0x97 : '<inventory_root>/system/chassis/motherboard/bios',
        0xda : '/org/openbmc/sensors/host/TurboAllowed',
    },
    'FRU_STR' : {
        'BOARD_1'    : '<inventory_root>/system/chassis/motherboard/cpu0',
        'BOARD_2'    : '<inventory_root>/system/chassis/motherboard/cpu1',
        'BOARD_3'    : '<inventory_root>/system/chassis/motherboard/cpu2',
        'BOARD_4'    : '<inventory_root>/system/chassis/motherboard/cpu3',
        'CHASSIS_5'  : '<inventory_root>/system/chassis/motherboard',
        'BOARD_5'    : '<inventory_root>/system/misc',
        'BOARD_6'    : '<inventory_root>/system/chassis/motherboard/membuf0',
        'BOARD_7'    : '<inventory_root>/system/chassis/motherboard/membuf1',
        'BOARD_8'    : '<inventory_root>/system/chassis/motherboard/membuf2',
        'BOARD_9'    : '<inventory_root>/system/chassis/motherboard/membuf3',
        'BOARD_10'   : '<inventory_root>/system/chassis/motherboard/membuf4',
        'BOARD_11'   : '<inventory_root>/system/chassis/motherboard/membuf5',
        'BOARD_12'   : '<inventory_root>/system/chassis/motherboard/membuf6',
        'BOARD_13'   : '<inventory_root>/system/chassis/motherboard/membuf7',
        'BOARD_14'   : '<inventory_root>/system/chassis/motherboard/membuf8',
        'BOARD_15'   : '<inventory_root>/system/chassis/motherboard/membuf9',
        'BOARD_16'   : '<inventory_root>/system/chassis/motherboard/membuf10',
        'BOARD_17'   : '<inventory_root>/system/chassis/motherboard/membuf11',
        'BOARD_18'   : '<inventory_root>/system/chassis/motherboard/membuf12',
        'BOARD_19'   : '<inventory_root>/system/chassis/motherboard/membuf13',
        'BOARD_20'   : '<inventory_root>/system/chassis/motherboard/membuf14',
        'BOARD_21'   : '<inventory_root>/system/chassis/motherboard/membuf15',
        'PRODUCT_22'   : '<inventory_root>/system/chassis/motherboard/dimm0',
        'PRODUCT_23'   : '<inventory_root>/system/chassis/motherboard/dimm1',
        'PRODUCT_24'   : '<inventory_root>/system/chassis/motherboard/dimm2',
        'PRODUCT_25'   : '<inventory_root>/system/chassis/motherboard/dimm3',
        'PRODUCT_26'   : '<inventory_root>/system/chassis/motherboard/dimm4',
        'PRODUCT_27'   : '<inventory_root>/system/chassis/motherboard/dimm5',
        'PRODUCT_28'   : '<inventory_root>/system/chassis/motherboard/dimm6',
        'PRODUCT_29'   : '<inventory_root>/system/chassis/motherboard/dimm7',
        'PRODUCT_30'   : '<inventory_root>/system/chassis/motherboard/dimm8',
        'PRODUCT_31'   : '<inventory_root>/system/chassis/motherboard/dimm9',
        'PRODUCT_32'   : '<inventory_root>/system/chassis/motherboard/dimm10',
        'PRODUCT_33'   : '<inventory_root>/system/chassis/motherboard/dimm11',
        'PRODUCT_34'   : '<inventory_root>/system/chassis/motherboard/dimm12',
        'PRODUCT_35'   : '<inventory_root>/system/chassis/motherboard/dimm13',
        'PRODUCT_36'   : '<inventory_root>/system/chassis/motherboard/dimm14',
        'PRODUCT_37'   : '<inventory_root>/system/chassis/motherboard/dimm15',
        'PRODUCT_38'   : '<inventory_root>/system/chassis/motherboard/dimm16',
        'PRODUCT_39'   : '<inventory_root>/system/chassis/motherboard/dimm17',
        'PRODUCT_40'   : '<inventory_root>/system/chassis/motherboard/dimm18',
        'PRODUCT_41'   : '<inventory_root>/system/chassis/motherboard/dimm19',
        'PRODUCT_42'   : '<inventory_root>/system/chassis/motherboard/dimm20',
        'PRODUCT_43'   : '<inventory_root>/system/chassis/motherboard/dimm21',
        'PRODUCT_44'   : '<inventory_root>/system/chassis/motherboard/dimm22',
        'PRODUCT_45'   : '<inventory_root>/system/chassis/motherboard/dimm23',
        'PRODUCT_46'   : '<inventory_root>/system/chassis/motherboard/dimm24',
        'PRODUCT_47'   : '<inventory_root>/system/chassis/motherboard/dimm25',
        'PRODUCT_48'   : '<inventory_root>/system/chassis/motherboard/dimm26',
        'PRODUCT_49'   : '<inventory_root>/system/chassis/motherboard/dimm27',
        'PRODUCT_50'   : '<inventory_root>/system/chassis/motherboard/dimm28',
        'PRODUCT_51'   : '<inventory_root>/system/chassis/motherboard/dimm29',
        'PRODUCT_52'   : '<inventory_root>/system/chassis/motherboard/dimm30',
        'PRODUCT_53'   : '<inventory_root>/system/chassis/motherboard/dimm31',
        'PRODUCT_54'   : '<inventory_root>/system/chassis/motherboard/dimm32',
        'PRODUCT_55'   : '<inventory_root>/system/chassis/motherboard/dimm33',
        'PRODUCT_56'   : '<inventory_root>/system/chassis/motherboard/dimm34',
        'PRODUCT_57'   : '<inventory_root>/system/chassis/motherboard/dimm35',
        'PRODUCT_58'   : '<inventory_root>/system/chassis/motherboard/dimm36',
        'PRODUCT_59'   : '<inventory_root>/system/chassis/motherboard/dimm37',
        'PRODUCT_60'   : '<inventory_root>/system/chassis/motherboard/dimm38',
        'PRODUCT_61'   : '<inventory_root>/system/chassis/motherboard/dimm39',
        'PRODUCT_62'   : '<inventory_root>/system/chassis/motherboard/dimm40',
        'PRODUCT_63'   : '<inventory_root>/system/chassis/motherboard/dimm41',
        'PRODUCT_64'   : '<inventory_root>/system/chassis/motherboard/dimm42',
        'PRODUCT_65'   : '<inventory_root>/system/chassis/motherboard/dimm43',
        'PRODUCT_66'   : '<inventory_root>/system/chassis/motherboard/dimm44',
        'PRODUCT_67'   : '<inventory_root>/system/chassis/motherboard/dimm45',
        'PRODUCT_68'   : '<inventory_root>/system/chassis/motherboard/dimm46',
        'PRODUCT_69'   : '<inventory_root>/system/chassis/motherboard/dimm47',
        'PRODUCT_70'   : '<inventory_root>/system/chassis/motherboard/dimm48',
        'PRODUCT_71'   : '<inventory_root>/system/chassis/motherboard/dimm49',
        'PRODUCT_72'   : '<inventory_root>/system/chassis/motherboard/dimm50',
        'PRODUCT_73'   : '<inventory_root>/system/chassis/motherboard/dimm51',
        'PRODUCT_74'   : '<inventory_root>/system/chassis/motherboard/dimm52',
        'PRODUCT_75'   : '<inventory_root>/system/chassis/motherboard/dimm53',
        'PRODUCT_76'   : '<inventory_root>/system/chassis/motherboard/dimm54',
        'PRODUCT_77'   : '<inventory_root>/system/chassis/motherboard/dimm55',
        'PRODUCT_78'   : '<inventory_root>/system/chassis/motherboard/dimm56',
        'PRODUCT_79'   : '<inventory_root>/system/chassis/motherboard/dimm57',
        'PRODUCT_80'   : '<inventory_root>/system/chassis/motherboard/dimm58',
        'PRODUCT_81'   : '<inventory_root>/system/chassis/motherboard/dimm59',
        'PRODUCT_82'   : '<inventory_root>/system/chassis/motherboard/dimm50',
        'PRODUCT_83'   : '<inventory_root>/system/chassis/motherboard/dimm61',
        'PRODUCT_84'   : '<inventory_root>/system/chassis/motherboard/dimm62',
        'PRODUCT_85'   : '<inventory_root>/system/chassis/motherboard/dimm63',
        'PRODUCT_86'   : '<inventory_root>/system/chassis/motherboard/dimm64',
        'PRODUCT_87'   : '<inventory_root>/system/chassis/motherboard/dimm65',
        'PRODUCT_88'   : '<inventory_root>/system/chassis/motherboard/dimm66',
        'PRODUCT_89'   : '<inventory_root>/system/chassis/motherboard/dimm67',
        'PRODUCT_90'   : '<inventory_root>/system/chassis/motherboard/dimm68',
        'PRODUCT_91'   : '<inventory_root>/system/chassis/motherboard/dimm69',
        'PRODUCT_92'   : '<inventory_root>/system/chassis/motherboard/dimm70',
        'PRODUCT_93'   : '<inventory_root>/system/chassis/motherboard/dimm71',
        'PRODUCT_94'   : '<inventory_root>/system/chassis/motherboard/dimm72',
        'PRODUCT_95'   : '<inventory_root>/system/chassis/motherboard/dimm73',
        'PRODUCT_96'   : '<inventory_root>/system/chassis/motherboard/dimm74',
        'PRODUCT_97'   : '<inventory_root>/system/chassis/motherboard/dimm75',
        'PRODUCT_98'   : '<inventory_root>/system/chassis/motherboard/dimm76',
        'PRODUCT_99'   : '<inventory_root>/system/chassis/motherboard/dimm77',
        'PRODUCT_100'   : '<inventory_root>/system/chassis/motherboard/dimm78',
        'PRODUCT_101'   : '<inventory_root>/system/chassis/motherboard/dimm79',
        'PRODUCT_102'   : '<inventory_root>/system/chassis/motherboard/dimm80',
        'PRODUCT_103'   : '<inventory_root>/system/chassis/motherboard/dimm81',
        'PRODUCT_104'   : '<inventory_root>/system/chassis/motherboard/dimm82',
        'PRODUCT_105'   : '<inventory_root>/system/chassis/motherboard/dimm83',
        'PRODUCT_106'   : '<inventory_root>/system/chassis/motherboard/dimm84',
        'PRODUCT_107'   : '<inventory_root>/system/chassis/motherboard/dimm85',
        'PRODUCT_108'   : '<inventory_root>/system/chassis/motherboard/dimm86',
        'PRODUCT_109'   : '<inventory_root>/system/chassis/motherboard/dimm87',
        'PRODUCT_110'   : '<inventory_root>/system/chassis/motherboard/dimm88',
        'PRODUCT_111'   : '<inventory_root>/system/chassis/motherboard/dimm89',
        'PRODUCT_112'   : '<inventory_root>/system/chassis/motherboard/dimm90',
        'PRODUCT_113'   : '<inventory_root>/system/chassis/motherboard/dimm91',
        'PRODUCT_114'   : '<inventory_root>/system/chassis/motherboard/dimm92',
        'PRODUCT_115'   : '<inventory_root>/system/chassis/motherboard/dimm93',
        'PRODUCT_116'   : '<inventory_root>/system/chassis/motherboard/dimm94',
        'PRODUCT_117'   : '<inventory_root>/system/chassis/motherboard/dimm95',
        'PRODUCT_118'   : '<inventory_root>/system/chassis/motherboard/dimm96',
        'PRODUCT_119'   : '<inventory_root>/system/chassis/motherboard/dimm97',
        'PRODUCT_120'   : '<inventory_root>/system/chassis/motherboard/dimm98',
        'PRODUCT_121'   : '<inventory_root>/system/chassis/motherboard/dimm99',
        'PRODUCT_122'   : '<inventory_root>/system/chassis/motherboard/dimm100',
        'PRODUCT_123'   : '<inventory_root>/system/chassis/motherboard/dimm101',
        'PRODUCT_124'   : '<inventory_root>/system/chassis/motherboard/dimm102',
        'PRODUCT_125'   : '<inventory_root>/system/chassis/motherboard/dimm103',
        'PRODUCT_126'   : '<inventory_root>/system/chassis/motherboard/dimm104',
        'PRODUCT_127'   : '<inventory_root>/system/chassis/motherboard/dimm105',
        'PRODUCT_128'   : '<inventory_root>/system/chassis/motherboard/dimm106',
        'PRODUCT_129'   : '<inventory_root>/system/chassis/motherboard/dimm107',
        'PRODUCT_130'   : '<inventory_root>/system/chassis/motherboard/dimm108',
        'PRODUCT_131'   : '<inventory_root>/system/chassis/motherboard/dimm109',
        'PRODUCT_132'   : '<inventory_root>/system/chassis/motherboard/dimm110',
        'PRODUCT_133'   : '<inventory_root>/system/chassis/motherboard/dimm111',
        'PRODUCT_134'   : '<inventory_root>/system/chassis/motherboard/dimm112',
        'PRODUCT_135'   : '<inventory_root>/system/chassis/motherboard/dimm113',
        'PRODUCT_136'   : '<inventory_root>/system/chassis/motherboard/dimm114',
        'PRODUCT_137'   : '<inventory_root>/system/chassis/motherboard/dimm115',
        'PRODUCT_138'   : '<inventory_root>/system/chassis/motherboard/dimm116',
        'PRODUCT_139'   : '<inventory_root>/system/chassis/motherboard/dimm117',
        'PRODUCT_140'   : '<inventory_root>/system/chassis/motherboard/dimm118',
        'PRODUCT_141'   : '<inventory_root>/system/chassis/motherboard/dimm119',
        'PRODUCT_142'   : '<inventory_root>/system/chassis/motherboard/dimm120',
        'PRODUCT_143'   : '<inventory_root>/system/chassis/motherboard/dimm121',
        'PRODUCT_144'   : '<inventory_root>/system/chassis/motherboard/dimm122',
        'PRODUCT_145'   : '<inventory_root>/system/chassis/motherboard/dimm123',
        'PRODUCT_146'   : '<inventory_root>/system/chassis/motherboard/dimm124',
        'PRODUCT_147'   : '<inventory_root>/system/chassis/motherboard/dimm125',
        'PRODUCT_148'   : '<inventory_root>/system/chassis/motherboard/dimm126',
        'PRODUCT_149'   : '<inventory_root>/system/chassis/motherboard/dimm127',
        'PRODUCT_150'   : '<inventory_root>/system/misc',
        'PRODUCT_151'   : '<inventory_root>/system/chassis/motherboard/bios',
    },
    'SENSOR' : {
        0x04 : '/org/openbmc/sensors/host/HostStatus',
        0x05 : '/org/openbmc/sensors/host/BootProgress',
        0x08 : '/org/openbmc/sensors/host/cpu0/OccStatus',
        0x09 : '/org/openbmc/sensors/host/cpu1/OccStatus',
        0x06 : '/org/openbmc/sensors/host/cpu2/OccStatus',
        0x07 : '/org/openbmc/sensors/host/cpu3/OccStatus',
        0x0c : '<inventory_root>/system/chassis/motherboard/cpu0',
        0x0e : '<inventory_root>/system/chassis/motherboard/cpu1',    
        0x03 : '<inventory_root>/system/chassis/motherboard/cpu2',
        0x0f : '<inventory_root>/system/chassis/motherboard/cpu3',    
        0x10 : '<inventory_root>/system/chassis/motherboard/dimm0',
        0x11 : '<inventory_root>/system/chassis/motherboard/dimm1',
        0x12 : '<inventory_root>/system/chassis/motherboard/dimm2',
        0x13 : '<inventory_root>/system/chassis/motherboard/dimm3',
        0x14 : '<inventory_root>/system/chassis/motherboard/dimm4',
        0x15 : '<inventory_root>/system/chassis/motherboard/dimm5',
        0x16 : '<inventory_root>/system/chassis/motherboard/dimm6',
        0x17 : '<inventory_root>/system/chassis/motherboard/dimm7',
        0x18 : '<inventory_root>/system/chassis/motherboard/dimm8',
        0x19 : '<inventory_root>/system/chassis/motherboard/dimm9',
        0x1a : '<inventory_root>/system/chassis/motherboard/dimm10',
        0x1b : '<inventory_root>/system/chassis/motherboard/dimm11',
        0x1c : '<inventory_root>/system/chassis/motherboard/dimm12',
        0x1d : '<inventory_root>/system/chassis/motherboard/dimm13',
        0x1e : '<inventory_root>/system/chassis/motherboard/dimm14',
        0x1f : '<inventory_root>/system/chassis/motherboard/dimm15',
        0x20 : '<inventory_root>/system/chassis/motherboard/dimm16',
        0x21 : '<inventory_root>/system/chassis/motherboard/dimm17',
        0x22 : '<inventory_root>/system/chassis/motherboard/dimm18',
        0x23 : '<inventory_root>/system/chassis/motherboard/dimm19',
        0x24 : '<inventory_root>/system/chassis/motherboard/dimm20',
        0x25 : '<inventory_root>/system/chassis/motherboard/dimm21',
        0x26 : '<inventory_root>/system/chassis/motherboard/dimm22',
        0x27 : '<inventory_root>/system/chassis/motherboard/dimm23',
        0x28 : '<inventory_root>/system/chassis/motherboard/dimm24',
        0x29 : '<inventory_root>/system/chassis/motherboard/dimm25',
        0x2a : '<inventory_root>/system/chassis/motherboard/dimm26',
        0x2b : '<inventory_root>/system/chassis/motherboard/dimm27',
        0x2c : '<inventory_root>/system/chassis/motherboard/dimm28',
        0x2d : '<inventory_root>/system/chassis/motherboard/dimm29',
        0x2e : '<inventory_root>/system/chassis/motherboard/dimm30',
        0x2f : '<inventory_root>/system/chassis/motherboard/dimm31',
        0x30 : '<inventory_root>/system/chassis/motherboard/dimm32',
        0x31 : '<inventory_root>/system/chassis/motherboard/dimm33',
        0x32 : '<inventory_root>/system/chassis/motherboard/dimm34',
        0x33 : '<inventory_root>/system/chassis/motherboard/dimm35',
        0x34 : '<inventory_root>/system/chassis/motherboard/dimm36',
        0x35 : '<inventory_root>/system/chassis/motherboard/dimm37',
        0x36 : '<inventory_root>/system/chassis/motherboard/dimm38',
        0x37 : '<inventory_root>/system/chassis/motherboard/dimm39',
        0x38 : '<inventory_root>/system/chassis/motherboard/dimm40',
        0x39 : '<inventory_root>/system/chassis/motherboard/dimm41',
        0x3a : '<inventory_root>/system/chassis/motherboard/dimm42',
        0x3b : '<inventory_root>/system/chassis/motherboard/dimm43',
        0x3c : '<inventory_root>/system/chassis/motherboard/dimm44',
        0x3d : '<inventory_root>/system/chassis/motherboard/dimm45',
        0x3e : '<inventory_root>/system/chassis/motherboard/dimm46',
        0x3f : '<inventory_root>/system/chassis/motherboard/dimm47',
        0x40 : '<inventory_root>/system/chassis/motherboard/dimm48',
        0x41 : '<inventory_root>/system/chassis/motherboard/dimm49',
        0x42 : '<inventory_root>/system/chassis/motherboard/dimm50',
        0x43 : '<inventory_root>/system/chassis/motherboard/dimm51',
        0x44 : '<inventory_root>/system/chassis/motherboard/dimm52',
        0x45 : '<inventory_root>/system/chassis/motherboard/dimm53',
        0x46 : '<inventory_root>/system/chassis/motherboard/dimm54',
        0x47 : '<inventory_root>/system/chassis/motherboard/dimm55',
        0x48 : '<inventory_root>/system/chassis/motherboard/dimm56',
        0x49 : '<inventory_root>/system/chassis/motherboard/dimm57',
        0x4a : '<inventory_root>/system/chassis/motherboard/dimm58',
        0x4b : '<inventory_root>/system/chassis/motherboard/dimm59',
        0x4c : '<inventory_root>/system/chassis/motherboard/dimm60',
        0x4d : '<inventory_root>/system/chassis/motherboard/dimm61',
        0x4e : '<inventory_root>/system/chassis/motherboard/dimm62',
        0x4f : '<inventory_root>/system/chassis/motherboard/dimm63',
        0x70 : '<inventory_root>/system/chassis/motherboard/dimm64',
        0x71 : '<inventory_root>/system/chassis/motherboard/dimm65',
        0x72 : '<inventory_root>/system/chassis/motherboard/dimm66',
        0x73 : '<inventory_root>/system/chassis/motherboard/dimm67',
        0x74 : '<inventory_root>/system/chassis/motherboard/dimm68',
        0x75 : '<inventory_root>/system/chassis/motherboard/dimm69',
        0x76 : '<inventory_root>/system/chassis/motherboard/dimm70',
        0x77 : '<inventory_root>/system/chassis/motherboard/dimm71',
        0x78 : '<inventory_root>/system/chassis/motherboard/dimm72',
        0x79 : '<inventory_root>/system/chassis/motherboard/dimm73',
        0x7a : '<inventory_root>/system/chassis/motherboard/dimm74',
        0x7b : '<inventory_root>/system/chassis/motherboard/dimm75',
        0x7c : '<inventory_root>/system/chassis/motherboard/dimm76',
        0x7d : '<inventory_root>/system/chassis/motherboard/dimm77',
        0x7e : '<inventory_root>/system/chassis/motherboard/dimm78',
        0x7f : '<inventory_root>/system/chassis/motherboard/dimm79',
        0x80 : '<inventory_root>/system/chassis/motherboard/dimm80',
        0x81 : '<inventory_root>/system/chassis/motherboard/dimm81',
        0x82 : '<inventory_root>/system/chassis/motherboard/dimm82',
        0x83 : '<inventory_root>/system/chassis/motherboard/dimm83',
        0x84 : '<inventory_root>/system/chassis/motherboard/dimm84',
        0x85 : '<inventory_root>/system/chassis/motherboard/dimm85',
        0x86 : '<inventory_root>/system/chassis/motherboard/dimm86',
        0x87 : '<inventory_root>/system/chassis/motherboard/dimm87',
        0x88 : '<inventory_root>/system/chassis/motherboard/dimm88',
        0x89 : '<inventory_root>/system/chassis/motherboard/dimm89',
        0x8a : '<inventory_root>/system/chassis/motherboard/dimm90',
        0x8b : '<inventory_root>/system/chassis/motherboard/dimm91',
        0x8c : '<inventory_root>/system/chassis/motherboard/dimm92',
        0x8d : '<inventory_root>/system/chassis/motherboard/dimm93',
        0x8e : '<inventory_root>/system/chassis/motherboard/dimm94',
        0x8f : '<inventory_root>/system/chassis/motherboard/dimm95',
        0x90 : '<inventory_root>/system/chassis/motherboard/dimm96',
        0x91 : '<inventory_root>/system/chassis/motherboard/dimm97',
        0x92 : '<inventory_root>/system/chassis/motherboard/dimm98',
        0x93 : '<inventory_root>/system/chassis/motherboard/dimm99',
        0x94 : '<inventory_root>/system/chassis/motherboard/dimm100',
        0x95 : '<inventory_root>/system/chassis/motherboard/dimm101',
        0x96 : '<inventory_root>/system/chassis/motherboard/dimm102',
        0x97 : '<inventory_root>/system/chassis/motherboard/dimm103',
        0x98 : '<inventory_root>/system/chassis/motherboard/dimm104',
        0x99 : '<inventory_root>/system/chassis/motherboard/dimm105',
        0x9a : '<inventory_root>/system/chassis/motherboard/dimm106',
        0x9b : '<inventory_root>/system/chassis/motherboard/dimm107',
        0x9c : '<inventory_root>/system/chassis/motherboard/dimm108',
        0x9d : '<inventory_root>/system/chassis/motherboard/dimm109',
        0x9e : '<inventory_root>/system/chassis/motherboard/dimm110',
        0x9f : '<inventory_root>/system/chassis/motherboard/dimm111',
        0xc0 : '<inventory_root>/system/chassis/motherboard/dimm112',
        0xc1 : '<inventory_root>/system/chassis/motherboard/dimm113',
        0xc2 : '<inventory_root>/system/chassis/motherboard/dimm114',
        0xc3 : '<inventory_root>/system/chassis/motherboard/dimm115',
        0xc4 : '<inventory_root>/system/chassis/motherboard/dimm116',
        0xc5 : '<inventory_root>/system/chassis/motherboard/dimm117',
        0xc6 : '<inventory_root>/system/chassis/motherboard/dimm118',
        0xc7 : '<inventory_root>/system/chassis/motherboard/dimm119',
        0xc8 : '<inventory_root>/system/chassis/motherboard/dimm120',
        0xc9 : '<inventory_root>/system/chassis/motherboard/dimm121',
        0xca : '<inventory_root>/system/chassis/motherboard/dimm122',
        0xcb : '<inventory_root>/system/chassis/motherboard/dimm123',
        0xcc : '<inventory_root>/system/chassis/motherboard/dimm124',
        0xcd : '<inventory_root>/system/chassis/motherboard/dimm125',
        0xce : '<inventory_root>/system/chassis/motherboard/dimm126',
        0xcf : '<inventory_root>/system/chassis/motherboard/dimm127',
        0x50 : '<inventory_root>/system/chassis/motherboard/cpu0/core0',
        0x51 : '<inventory_root>/system/chassis/motherboard/cpu0/core1',
        0x52 : '<inventory_root>/system/chassis/motherboard/cpu0/core2',
        0x53 : '<inventory_root>/system/chassis/motherboard/cpu0/core3',
        0x54 : '<inventory_root>/system/chassis/motherboard/cpu0/core4',
        0x55 : '<inventory_root>/system/chassis/motherboard/cpu0/core5',
        0x56 : '<inventory_root>/system/chassis/motherboard/cpu0/core6',
        0x57 : '<inventory_root>/system/chassis/motherboard/cpu0/core7',
        0x58 : '<inventory_root>/system/chassis/motherboard/cpu0/core8',
        0x59 : '<inventory_root>/system/chassis/motherboard/cpu0/core9',
        0x5a : '<inventory_root>/system/chassis/motherboard/cpu0/core10',
        0x5b : '<inventory_root>/system/chassis/motherboard/cpu0/core11',
        0x5c : '<inventory_root>/system/chassis/motherboard/cpu1/core0',
        0x5d : '<inventory_root>/system/chassis/motherboard/cpu1/core1',
        0x65 : '<inventory_root>/system/chassis/motherboard/cpu1/core2',
        0x66 : '<inventory_root>/system/chassis/motherboard/cpu1/core3',
        0x67 : '<inventory_root>/system/chassis/motherboard/cpu1/core4',
        0x68 : '<inventory_root>/system/chassis/motherboard/cpu1/core5',
        0x69 : '<inventory_root>/system/chassis/motherboard/cpu1/core6',
        0x6a : '<inventory_root>/system/chassis/motherboard/cpu1/core7',
        0x6b : '<inventory_root>/system/chassis/motherboard/cpu1/core8',
        0x6c : '<inventory_root>/system/chassis/motherboard/cpu1/core9',
        0x6d : '<inventory_root>/system/chassis/motherboard/cpu1/core10',
        0x6e : '<inventory_root>/system/chassis/motherboard/cpu1/core11',
        0x6f : '<inventory_root>/system/chassis/motherboard/cpu2/core0',
        0xb7 : '<inventory_root>/system/chassis/motherboard/cpu2/core1',
        0xb8 : '<inventory_root>/system/chassis/motherboard/cpu2/core2',
        0xb9 : '<inventory_root>/system/chassis/motherboard/cpu2/core3',
        0xba : '<inventory_root>/system/chassis/motherboard/cpu2/core4',
        0xbb : '<inventory_root>/system/chassis/motherboard/cpu2/core5',
        0xbc : '<inventory_root>/system/chassis/motherboard/cpu2/core6',
        0xbd : '<inventory_root>/system/chassis/motherboard/cpu2/core7',
        0xbe : '<inventory_root>/system/chassis/motherboard/cpu2/core8',
        0xbf : '<inventory_root>/system/chassis/motherboard/cpu2/core9',
        0xd0 : '<inventory_root>/system/chassis/motherboard/cpu2/core10',
        0xd1 : '<inventory_root>/system/chassis/motherboard/cpu2/core11',
        0xd2 : '<inventory_root>/system/chassis/motherboard/cpu3/core0',
        0xd3 : '<inventory_root>/system/chassis/motherboard/cpu3/core1',
        0xd4 : '<inventory_root>/system/chassis/motherboard/cpu3/core2',
        0xd5 : '<inventory_root>/system/chassis/motherboard/cpu3/core3',
        0xd6 : '<inventory_root>/system/chassis/motherboard/cpu3/core4',
        0xd7 : '<inventory_root>/system/chassis/motherboard/cpu3/core5',
        0xd9 : '<inventory_root>/system/chassis/motherboard/cpu3/core6',
        0xdb : '<inventory_root>/system/chassis/motherboard/cpu3/core7',
        0xdc : '<inventory_root>/system/chassis/motherboard/cpu3/core8',
        0xdd : '<inventory_root>/system/chassis/motherboard/cpu3/core9',
        0xde : '<inventory_root>/system/chassis/motherboard/cpu3/core10',
        0xdf : '<inventory_root>/system/chassis/motherboard/cpu3/core11',
        0xf0 : '<inventory_root>/system/chassis/motherboard/membuf0',
        0xf1 : '<inventory_root>/system/chassis/motherboard/membuf1',
        0xf2 : '<inventory_root>/system/chassis/motherboard/membuf2',
        0xf3 : '<inventory_root>/system/chassis/motherboard/membuf3',
        0xf4 : '<inventory_root>/system/chassis/motherboard/membuf4',
        0xf5 : '<inventory_root>/system/chassis/motherboard/membuf5',
        0xf6 : '<inventory_root>/system/chassis/motherboard/membuf6',
        0xf7 : '<inventory_root>/system/chassis/motherboard/membuf7',
        0xf8 : '<inventory_root>/system/chassis/motherboard/membuf8',
        0xf9 : '<inventory_root>/system/chassis/motherboard/membuf9',
        0xfa : '<inventory_root>/system/chassis/motherboard/membuf10',
        0xfb : '<inventory_root>/system/chassis/motherboard/membuf11',
        0xfc : '<inventory_root>/system/chassis/motherboard/membuf12',
        0xfd : '<inventory_root>/system/chassis/motherboard/membuf13',
        0xfe : '<inventory_root>/system/chassis/motherboard/membuf14',
        0xa0 : '<inventory_root>/system/chassis/motherboard/membuf15',
        0x5f : '/org/openbmc/sensors/host/BootCount',
        0x60 : '<inventory_root>/system/chassis/motherboard',
        0x61 : '<inventory_root>/system/systemevent',
        0x62 : '<inventory_root>/system/powerlimit',
        0x63 : '<inventory_root>/system/chassis/motherboard/refclock',
        0x64 : '<inventory_root>/system/chassis/motherboard/pcieclock',
        0xb1 : '<inventory_root>/system/chassis/motherboard/todclock',
        0xb2 : '<inventory_root>/system/chassis/motherboard/apss',
        0xb3 : '/org/openbmc/sensors/host/powercap',
        0xb5 : '/org/openbmc/sensors/host/OperatingSystemStatus',
        0xb6 : '<inventory_root>/system/chassis/motherboard/pcielink',
    },
    'GPIO_PRESENT' : {}
}

GPIO_CONFIG = {}
GPIO_CONFIG['BMC_POWER_UP'] = \
        {'gpio_pin': 'E1', 'direction': 'out'}
GPIO_CONFIG['SYS_PWROK_BUFF'] = \
        {'gpio_pin': 'D2', 'direction': 'in'}
GPIO_CONFIG['BMC_WD_CLEAR_PULSE_N'] = \
        {'gpio_pin': 'N4', 'direction': 'out'}
GPIO_CONFIG['CM1_OE_R_N'] = \
        {'gpio_pin': 'Q6', 'direction': 'out'}
GPIO_CONFIG['BMC_CP0_RESET_N'] = \
        {'gpio_pin': 'O2', 'direction': 'out'}
GPIO_CONFIG['PSU_PG'] = \
        {'gpio_pin': 'J2', 'direction': 'in'}
GPIO_CONFIG['PEX8718_DEVICES_RESET_N'] = \
        {'gpio_pin': 'B6', 'direction': 'out'}
GPIO_CONFIG['CP0_DEVICES_RESET_N'] = \
        {'gpio_pin': 'N3', 'direction': 'out'}
GPIO_CONFIG['CP1_DEVICES_RESET_N'] = \
        {'gpio_pin': 'N5', 'direction': 'out'}
GPIO_CONFIG['CP2_DEVICES_RESET_N'] = \
        {'gpio_pin': 'P0', 'direction': 'out'}
GPIO_CONFIG['CP3_DEVICES_RESET_N'] = \
        {'gpio_pin': 'P1', 'direction': 'out'}
#GPIO_CONFIG['IDBTN']       = \
#        { 'gpio_pin': 'Q7', 'direction': 'out' }
GPIO_CONFIG['FSI_DATA'] = \
        {'gpio_pin': 'A5', 'direction': 'out'}
GPIO_CONFIG['FSI_CLK'] = \
        {'gpio_pin': 'A4', 'direction': 'out'}
GPIO_CONFIG['FSI_ENABLE'] = \
        {'gpio_pin': 'D0', 'direction': 'out'}
GPIO_CONFIG['CRONUS_SEL'] = \
        {'gpio_pin': 'A6', 'direction': 'out'}
#GPIO_CONFIG['BMC_CPLD_RESET'] = \
#        {'gpio_pin': 'R7', 'direction': 'out'}

GPIO_CONFIG['POWER_BUTTON'] = \
        {'gpio_pin': 'E0', 'direction': 'both'}
GPIO_CONFIG['RESET_BUTTON'] = \
        {'gpio_pin': 'E2', 'direction': 'both'}
GPIO_CONFIG['CHECKSTOP'] = \
        {'gpio_pin': 'P5', 'direction': 'falling'}

GPIO_CONFIG['PS0_PRES_N'] = \
        {'gpio_pin': 'P7', 'direction': 'in'}
GPIO_CONFIG['PS1_PRES_N'] = \
        {'gpio_pin': 'N0', 'direction': 'in'}

GPIO_CONFIGS = {
    'power_config' : {
        'power_good_in' : 'SYS_PWROK_BUFF',
        'power_up_outs' : [
            ('BMC_POWER_UP', False),
        ],
        'reset_outs' : [
            ('CM1_OE_R_N', True),
            ('BMC_CP0_RESET_N', False),
#            ('BMC_CFAM_RESET_N_R', False),
        ],
        'pci_reset_outs': [
            # net name, polarity, reset hold
            # if 'reset hold' set to 'True', BMC will hold pci reset until host CPU ready to drive PCI
            ('PEX8718_DEVICES_RESET_N', False, True),
            ('CP0_DEVICES_RESET_N', False, True),
            ('CP1_DEVICES_RESET_N', False, True),
            ('CP2_DEVICES_RESET_N', False, True),
            ('CP3_DEVICES_RESET_N', False, True),
        ],
    },
    'hostctl_config' : {
        'fsi_data' : 'FSI_DATA',
        'fsi_clk' : 'FSI_CLK',
        'fsi_enable' : 'FSI_ENABLE',
        'cronus_sel' : 'CRONUS_SEL',
        'optionals' : [
#            ('IDBTN', False),
        ],
    },
}


# Miscellaneous non-poll sensor with system specific properties.
# The sensor id is the same as those defined in ID_LOOKUP['SENSOR'].
MISC_SENSORS = {
    0x5f : { 'class' : 'BootCountSensor' },
    0x05 : { 'class' : 'BootProgressSensor' },
    0xb5 : { 'class' : 'OperatingSystemStatusSensor' },
}

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
